{
 "title": "Micrometer Default Metrics",
 "description": "Default metrics emitted by Micrometer for GC, Memory, Threads, CPU usage, etc.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(logback_events_total, app)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(logback_events_total{app=\"$app\"}, instance)"
    }
   },
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{app=\"$app\", instance=~\"$instance\"}, uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Global bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(tomcat_global_received_bytes_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "received"
      },
      {
       "expr": "sum(rate(tomcat_global_sent_bytes_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Error / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tomcat_servlet_error_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "servlet"
      },
      {
       "expr": "sum(rate(tomcat_global_error_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Sessions / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tomcat_sessions_created_sessions_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "created"
      },
      {
       "expr": "sum(rate(tomcat_sessions_expired_sessions_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "expired"
      },
      {
       "expr": "sum(rate(tomcat_sessions_rejected_sessions_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "rejected"
      }
     ]
    },
    {
     "title": "Global Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(tomcat_global_request_seconds_sum{app=\"$app\", instance=~\"$instance\"}[1m])) / sum(rate(tomcat_global_request_seconds_count{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "avg"
      },
      {
       "expr": "max(tomcat_global_request_max_seconds{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Servlet Requests latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(tomcat_servlet_request_seconds_sum{app=\"$app\", instance=~\"$instance\"}[1m])) / sum(rate(tomcat_servlet_request_seconds_count{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "avg"
      },
      {
       "expr": "max(tomcat_servlet_request_max_seconds{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(tomcat_connections_current_connections{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "current value"
      },
      {
       "expr": "avg(tomcat_connections_keepalive_current_connections{app=\"$app\", instance=~\"$instance\"}) ",
       "legendFormat": "keepliave current avg"
      },
      {
       "expr": "avg(tomcat_connections_config_max_connections{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(tomcat_threads_busy_threads{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "busy"
      },
      {
       "expr": "avg(tomcat_threads_current_threads{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "current"
      },
      {
       "expr": "avg(tomcat_threads_config_max_threads{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Cache / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tomcat_cache_hit_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "hit"
      },
      {
       "expr": "sum(rate(tomcat_cache_access_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "access"
      }
     ]
    },
    {
     "title": "Alive Max latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(tomcat_sessions_alive_max_seconds{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(tomcat_sessions_active_current_sessions{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "current avg"
      },
      {
       "expr": "avg(tomcat_sessions_active_max_sessions{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Http Server Requests",
     "type": "timeseries",
     "description": "Information regarding HTTP requests",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (uri, status) (rate(http_server_requests_seconds_count{app=\"$app\", instance=~\"$instance\", uri=~\"$uri\"}[1m]))"
      }
     ]
    },
    {
     "title": "Http Server Requests Latency",
     "type": "timeseries",
     "description": "Information regarding HTTP requests latency",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"$app\", instance=~\"$instance\", uri=~\"$uri\"}[1m])) / sum(rate(http_server_requests_seconds_count{app=\"$app\", instance=~\"$instance\", uri=~\"$uri\"}[1m])) ",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Http Server Requests Max Latency",
     "type": "timeseries",
     "description": "Information regarding HTTP requests latency",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (uri, status) (http_server_requests_seconds_max{app=\"$app\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Logback",
     "type": "timeseries",
     "description": "Number of error level events that made it to the logs",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (level) (rate(logback_events_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Pause: End of Minor GC - Avg",
     "type": "timeseries",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (cause) (rate(jvm_gc_pause_seconds_sum{app=\"$app\", action=\"end of minor GC\"}[1m])) / sum by (cause) (rate(jvm_gc_pause_seconds_count{app=\"$app\", action=\"end of minor GC\"}[1m]))",
       "legendFormat": "avg: {{cause}}"
      },
      {
       "expr": "sum by (cause) (rate(jvm_gc_pause_seconds_sum{app=\"$app\", action=\"end of minor GC\"}[1m])) / sum by (cause) (rate(jvm_gc_pause_seconds_count{app=\"$app\", action=\"end of minor GC\"}[1m]))",
       "legendFormat": "max: {{cause}}"
      }
     ]
    },
    {
     "title": "GC Pause: End of Minor GC - Max",
     "type": "timeseries",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 15, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (cause) (jvm_gc_pause_seconds_max{app=\"$app\", action=\"end of minor GC\", instance=~\"$instance\"})",
       "legendFormat": "avg: {{cause}}"
      },
      {
       "expr": "max by (cause) (jvm_gc_pause_seconds_max{app=\"$app\", action=\"end of minor GC\", instance=~\"$instance\"})",
       "legendFormat": "max: {{cause}}"
      }
     ]
    },
    {
     "title": "End of minor GC Triggers / sec",
     "type": "timeseries",
     "description": "#times minor gc was triggered / sec",
     "gridPos": { "h": 15, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (cause) (rate(jvm_gc_pause_seconds_count{app=\"$app\", action=\"end of minor GC\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{cause}}"
      }
     ]
    },
    {
     "title": "GC Pause: End of Major GC",
     "type": "timeseries",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{app=\"$app\", action=\"end of major GC\"}[1m]) / rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[1m])",
       "legendFormat": "avg: {{cause}}"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{app=\"$app\", action=\"end of major GC\", instance=~\"$instance\"}",
       "legendFormat": "max: {{cause}}"
      }
     ]
    },
    {
     "title": "Major GC Triggers / sec",
     "type": "timeseries",
     "description": "#times major gc was triggered / sec",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (cause) (rate(jvm_gc_pause_seconds_count{app=\"$app\", action=\"end of major GC\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{cause}}"
      }
     ]
    },
    {
     "title": "GC: Live Data Size",
     "type": "timeseries",
     "description": "Size of long-lived heap memory pool after reclamation",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_live_data_size_bytes{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "GC: Allocated Memory / sec",
     "type": "timeseries",
     "description": "Incremented for an increase in the size of the (young) heap memory pool after one GC to before the next",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_memory_allocated_bytes_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "GC: Promoted Memory / sec",
     "type": "timeseries",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_memory_promoted_bytes_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "GC: Max Size of long lived memory pool",
     "type": "timeseries",
     "description": "Max size of long-lived heap memory pool",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_gc_max_data_size_bytes{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap: Used Memory",
     "type": "timeseries",
     "description": "The amount of used memory",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (id) (jvm_memory_used_bytes{app=\"$app\", area=\"heap\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Heap: Committed Memory",
     "type": "timeseries",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (id) (jvm_memory_committed_bytes{app=\"$app\", area=\"heap\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Heap: Max Memory",
     "type": "timeseries",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (id) (jvm_memory_max_bytes{app=\"$app\", area=\"heap\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "NonHeap: Used Memory",
     "type": "timeseries",
     "description": "The amount of used memory",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (id) (jvm_memory_used_bytes{app=\"$app\", area=\"nonheap\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "NonHeap: Committed Memory",
     "type": "timeseries",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (id) (jvm_memory_committed_bytes{app=\"$app\", area=\"nonheap\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "NonHeap: Max Memory",
     "type": "timeseries",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (id) (jvm_memory_max_bytes{app=\"$app\", area=\"nonheap\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer: Used Memory",
     "type": "timeseries",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (id) (jvm_buffer_memory_used_bytes{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer: Total Capacity",
     "type": "timeseries",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (id) (jvm_buffer_total_capacity_bytes{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer: Count",
     "type": "timeseries",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (id) (jvm_buffer_count_buffers{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Avg (% Memory Usage After GC)",
     "type": "timeseries",
     "description": "The percentage of long-lived heap pool used after the last GC event, in the range [0..1]",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (area, pool) (jvm_memory_usage_after_gc_percent{app=\"$app\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Thread States",
     "type": "timeseries",
     "description": "The current number of threads having NEW state",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state) (jvm_threads_states_threads{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Live Threads",
     "type": "timeseries",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_threads_live_threads{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Daemon Threads",
     "type": "timeseries",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_threads_daemon_threads{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Peak Threads",
     "type": "timeseries",
     "description": "The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_threads_peak_threads{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "timeseries",
     "description": "The \"recent cpu usage\" for the Java Virtual Machine process",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(process_cpu_usage{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Open files count",
     "type": "timeseries",
     "description": "The open file descriptor count",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(process_files_open_files{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System CPU Usage",
     "type": "timeseries",
     "description": "The \"recent cpu usage\" for the whole system",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "sum(system_cpu_count{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "System Load Average",
     "type": "timeseries",
     "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(system_load_average_1m{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "Class",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Loaded classes / instance",
     "type": "timeseries",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(jvm_classes_loaded_classes{app=\"$app\", instance=~\"$instance\"})",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Unloaded classes / sec",
     "type": "timeseries",
     "description": "The number of classes unloaded / sec since the Java virtual machine has started execution",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_classes_unloaded_classes_total{app=\"$app\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "value"
      }
     ]
    }
   ]
  }
 ]
}